@startuml
Class Userinput{

takes user input
+String name
+String auhtor
+String filepath
+String JS
+String CSS
+String  Html

}
Class generateWebsite{
create output file
+Website for site
+Website for html
+JS folder
+CSS folder

}

@enduml